---
- hosts: all
  remote_user: root
  become: True
  tasks:
    - firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        zone: public

    - name: reload firewalld
      command: firewall-cmd --reload
